ALTER TABLE "findings" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "findings" ADD COLUMN IF NOT EXISTS "function" VARCHAR(255);
ALTER TABLE "findings" ADD COLUMN IF NOT EXISTS "confidence" DOUBLE PRECISION DEFAULT 0.5;
ALTER TABLE "findings" ADD COLUMN IF NOT EXISTS "codeSnippet" TEXT;
ALTER TABLE "findings" ADD COLUMN IF NOT EXISTS "remediationSteps" TEXT[] DEFAULT ARRAY[]::TEXT[];
